# Generated by Django 5.0.1 on 2024-01-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_floor', models.IntegerField()),
                ('room_capacity', models.IntegerField()),
                ('room_price', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
                ('room_status', models.CharField(max_length=50)),
                ('room_description', models.CharField(max_length=200)),
            ],
        ),
    ]
