# Generated by Django 5.0.1 on 2024-01-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
