# Generated by Django 5.0.1 on 2024-01-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hotelroom_check_in_hotelroom_check_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_floor', models.IntegerField()),
                ('room_capacity', models.IntegerField()),
                ('room_price', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
                ('room_status', models.CharField(max_length=50)),
                ('room_description', models.CharField(max_length=200)),
                ('booking_name', models.CharField(max_length=50)),
                ('booking_email', models.EmailField(max_length=50)),
                ('booking_phone', models.IntegerField()),
                ('booking_check_in', models.DateField()),
                ('booking_check_out', models.DateField()),
                ('booking_adults', models.IntegerField()),
                ('booking_children', models.IntegerField()),
                ('booking_infants', models.IntegerField()),
                ('booking_total', models.IntegerField()),
                ('booking_status', models.CharField(max_length=50)),
                ('booking_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='check_out',
        ),
    ]
