# Generated by Django 5.0.1 on 2024-02-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hotelroombooking_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_capacity', models.IntegerField()),
                ('booking_name', models.CharField(max_length=50)),
                ('booking_check_in', models.DateField()),
                ('booking_check_out', models.DateField()),
                ('booking_person', models.IntegerField()),
                ('booking_created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=False)),
            ],
        ),
    ]
