# Generated by Django 5.0.1 on 2024-02-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bookingroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelRoomBooking',
        ),
    ]
